### ISSUE TITLE
Unavailable videos

### ISSUE THREAD

**Issue by pfabreu** [s9xie/Mini-Kinetics-200#2]
Since iterating on Kinetics is unfeasible this seemed like a better solution, so thank you. However some of these videos are not available. For example (on the validation set):

`TypeError: b'ERROR: 7LSJ2Ryv1a8: YouTube said: This video is unavailable.\n' is not JSON serializable
`

Which is indeed true, just go to https://www.youtube.com/watch?v=7LSJ2Ryv1a8
Do you have an updated list?

**Comment by s9xie** [comment]
Hi Pedro, this is unfortunately inevitable -- Kinetics regularly removes invalid videos on Youtube too.
My suggestion is just skipping the unavailable videos for now. In our experience, a few missing videos won't change the reported accuracy. We might update the list once a while too. Pull requests are also welcomed.

**Comment by pfabreu** [comment]
Thank you for your answer. I made a fork and I'm gonna try to integrate a functionality that rebuilds the mini-Kinetics lists by sampling the full Kinetics for a new video of that class when one of them is unavailable.
